### ISSUE TITLE
tests are failing - company name not properly loaded

### ISSUE THREAD

**Issue by ameeno** [eracle/linkedin#19]
Hi, i have noticed via vnc that chrome and selenium crashes after logging in and going to connections.
i cannot actually see any activity just the ubuntu desktop.

what could be wrong?

**Comment by liuxilai2012** [comment]
My problem seems the same. Here is  my log. I don't know how to solve it.

![maketestsfault](https://user-images.githubusercontent.com/28869362/49380202-09df3b80-f74c-11e8-9bac-7265ff25f9ba.png)

![makedev](https://user-images.githubusercontent.com/28869362/49380233-24b1b000-f74c-11e8-86d7-fdc264ec6e3b.png)

**Comment by ameeno** [comment]
any luck with this issue?

**Comment by eracle** [comment]
Thanks everybody for the comments, I will have a look at this on the weekend. I'll keep you posted.

**Comment by eracle** [comment]
Guys, sorry I will have a look at it after the 20th of December.

**Comment by ameeno** [comment]
hello, is there any updates here? I tried again today.

**Comment by eracle** [comment]
The problem here is the Company name is not succesfully extracted.

**Comment by eracle** [comment]
tests are currently skipped and outdate. 
btw code is working
