### ISSUE TITLE
Can this api scrape the profile without "999"?

### ISSUE THREAD

**Issue by Frankjunyulin** [eracle/linkedin#3]
I am struggling with scraping people profile from linkedin. I always get error code "999" while scraping.  Have you solved this kind of issue?

**Comment by eracle** [comment]
Have you seen this [stackoverflow question](https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin)?

**Comment by eracle** [comment]
It never gave me such an error. Go ahead with the tutorial.
