### ISSUE TITLE
LinkedIn data structure change

### ISSUE THREAD

**Issue by Kaan191** [eracle/linkedin#5]
Hi - I have limited programming knowledge but read up enough to make good use of your code (thanks!). 

LinkedIn has overhauled how it presents position information in a Person’s Jobs history. Chiefly, if a Person has more than one role in a company, LinkedIn now collapses those positions under a single Company header, as opposed to for every such position. The output now is only the top role in this new ‘nest’ of roles, and the Company field yields ‘null’. I’ll spend the weekend looking at the code but unfortunately I lack the raw programming skill to do much about it (for now). 

Wanted to bring this to your attention. 

Cheers
Kaan

**Comment by eracle** [comment]
Hello @Kaan191 , thanks for the heads up and sorry for the delay on the response.
About the issue: did you close it because the issue is not happening again or did you manage to solve it?
