### ISSUE TITLE
Adapting for comment scraping?

### ISSUE THREAD

**Issue by Tylersuard** [eracle/linkedin#58]
Hello.  I have a single post with over 10,000 comments, and I need to scrape every one of them.  How would I go about adapting this code to do that?
Thank you for your help,
Tyler S

**Comment by Gugerty** [comment]
Python's Scrappy would do that rather nicely and put it into either a
spreadsheet or an html static page :D

**Comment by Tylersuard** [comment]
Thank you!

**Comment by eracle** [comment]
If everything is fine, I close the issue.
