### ISSUE TITLE
Spider closed (finished)

### ISSUE THREAD

**Issue by manashan** [eracle/linkedin#90]
I tried to run this repo but I get this error after a single run.
![Screenshot_2](https://user-images.githubusercontent.com/67643821/195150697-b484647c-ff4c-4412-8d41-e07608a48726.png)

**Comment by manashan** [comment]
Sorry when I prased start on docker-scrapy its working. I am using visibility scraper.
How can I make this a loop?
What's the recommended amount of times should I run in a day?

**Comment by eracle** [comment]
On lemlist they suggest doing an action every 20 minutes only during working schedules. But that is like messages or connection requests, for scraping I don't know
